### ISSUE TITLE
Can't log in via console

### ISSUE THREAD

**Issue by maxkraft7** [Tob1asDocker/rpi-mariadb#1]
this is my docker-compose:

```
services:
  mariadb:
    container_name: mariadb
    image: tobi312/rpi-mariadb
    networks:
        mynet:
            aliases:
                - database
    environment:
    - MYSQL_ROOT_PASSWORD=topsecret
    ports:
    - 3306:3306
```

But when I turn on a console on that container and type:

> mariadb -u root -p
> (then typing in the password)

I get an access denied error back, do you know what might could cause that error?
