### ISSUE TITLE
feature-request - Install curl in alpine for running scripts

### ISSUE THREAD

**Issue by bf8392** [Tob1asDocker/rpi-mariadb#4]
Hi =) I love your Image =) Just tested it and it's the only good and up-to-date one I know for rpi =). Can you please add curl to your 10.4/10.5 alpine image, and change the tags to something that points out which image is stable and which not =). I just readed from the docs that 10.5 is not stable...

I use apprise to notify my nextcloud when the database-Backup script has run =)

thanks for the great development =)

**Comment by Tob1as** [comment]
Hi,

in offical MariaDB image `curl` (and `wget`) is also not present. I'll have to think about that...

I have a suggestion:

Dockerfile:
```dockerfile
ARG MARIADB_VERSION=10.4
FROM tobi312/rpi-mariadb:${MARIADB_VERSION}-alpine
RUN apk --no-cache add curl
```
docker-compose-yml (with build instruction):

```yml
version: '2.4'

services:
  mariadb:
    build:
      context: ./
      dockerfile: Dockerfile
    image: local-mariadb:curl
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./mariadb:/var/lib/mysql:rw
    environment:
      #TZ: Europe/Berlin
      #MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - 3306:3306
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1
      #test:  mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
```

Or you use `wget` this is default included in the alpine image. 

I will not change the tags, I think the users should read the Docs. ;-) 
Note: The new Alpine Version 3.13 contains MariaDB 10.5([*](https://pkgs.alpinelinux.org/packages?name=mariadb&branch=v3.13)), so in future (when i have time to test) i change the Image from `edge` to `3.13` and set my image to stable.
